Vagrant.configure("2") do |config|
	config.vm.box = "ubuntu/jammy64"
    config.vm.box_version = "20241002.0.0"

	config.vm.network "private_network", ip: "192.168.56.17"
	config.vm.network "public_network"

	# Sync host './scripts' directory (relative to Vagrantfile) to guest '/opt/scripts'
	config.vm.synced_folder "./scripts", "/opt/scripts"

	config.vm.provider "virtualbox" do |vb|
		vb.memory = "1024"
		vb.cpus = 2
	end
end
